@startuml

object users {
    ID
    username
    email
    password
    fk_roleID
}

object roles {
    ID
    name
}

object photos {
    ID
    title
    description
}

object hashtags {
    ID
    name
}

object users_uploaded_photos {
    ID
    fk_userID
    fk_photoID
}

object users_profile_photos {
    ID
    fk_userID
    fk_photoID
}

object hashtags_to_photos {
    ID
    fk_hashtagID
    fk_photoID
}

object favourites {
    ID
    fk_userID
    fk_photoID
}

hashtags --> hashtags_to_photos 
photos --> hashtags_to_photos 

photos --> favourites
users --> favourites

users --> users_uploaded_photos 
photos --> users_uploaded_photos 

users --> users_profile_photos
photos --> users_profile_photos

roles --> users


@enduml